name: phase-change-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21
  - scipy=1.7
  - matplotlib=3.5
  - pandas=1.3
  - jupyter=1.0
  - notebook=6.4
  - ipython=7.27
  - seaborn=0.11
  - tqdm=4.62
  - pytest=6.2
  - pip
  - pip:
    - -e .
